config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  root 'books#index'

  resources :books do
    collection do
      post :import
      get :export
      post :scrape
    end
  end

  resources :vocabularies do
    collection do
      get :book_vocab
      get :search
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
# == Schema Information

# Table: books

# id													:bigint
# title: 											:text
# created_at: 								:datatime
# updated_at: 								:datatime

class Book < ApplicationRecord
  has_many :vocabularies
  has_many :scrapings

  has_many :author_books
  has_many :authors, through: :author_books

  validates :title, presence: true

  def self.book_title?(book_id)
    book = Book.find(book_id)
    book.title
  end

  # 以下サービス層に書くか
  def self.book_author?(book)
    author_book = AuthorBook.find_by(book_id: book.id)
    author = Author.find(author_book.author_id)
    author.name
  end

  def self.vocabulary_quantity?(book)
    Vocabulary.where(book_id: book.id).count
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Import

  def index
    @books = Book.all.page(params[:page])
  end

  def create; end

  def new; end

  def show; end

  def import
    # fileはtmpに自動で一時保存される
    Import::ImportCsv.import(params[:file])
    redirect_to root_url, notice: '本のインポートが完了しました'
  end

  def export
    book = Book.find(params[:book_id])
    vocabularies = Vocabulary.where(book_id: book.id, export_at: [nil, ''])
    ApplicationRecord.transaction do
      respond_to do |format|
        format.html
        format.csv do |_csv|
          generate_csv(vocabularies, book)
        end
      end
      current_time = DateTime.now
      vocabularies.each do |vocabulary|
        vocabulary.update!(export_at: current_time)
      end
    end
  end

  def scrape
    book_id = params[:book_id]
    ScrapeVocab.perform_later(book_id)
    redirect_to root_url, notice: 'スクレイピングを開始しました'
  end

  private

  def generate_csv(vocabularies, book)
    csv = CSV.generate do |csv|
      vocabularies.each do |vocabulary|
        csv.add_row([
                      vocabulary.word,
                      vocabulary.phonics,
                      vocabulary.example,
                      vocabulary.definition
                    ])
      end
    end
    time_now = Time.zone.now.strftime('%Y%m%d%H%M%S')
    send_data csv, filename: "Vocabularies_#{book.title}_#{time_now}.csv", type: :csv
  end
end

app/views/books/index.html.slim
h1
  | 書籍一覧
div.import.conatiner
	= form_tag import_books_path, multipart: true do
		div.row
			div.col-9
				= file_field_tag :file, class: 'form-control'
			div.col
				= submit_tag "インポート", class: 'btn btn-success'
table.table
  thead
    tr
      th ID
      th Title
      th Author
      th Vocabulary
      th Wating
      th Done
      th Scrape
      th Export
      th Exported
  tbody
    - @books.each do |book|
      tr
        td = book.id
        td = book.title
        td = Book.book_author?(book)
        td = link_to "#{Book.vocabulary_quantity?(book)}", book_vocab_vocabularies_path(book: book), {class: "text-decoration-none"}
        td = Vocabulary.vocab_not_scraped?(book)
        td = Vocabulary.count_done(book)
        td = button_to 'Start Scrape', scrape_books_path, method: :post, params: {book_id: book.id}, class: 'btn btn-success'
        td = button_to 'Export CSV', export_books_path(format: :csv), method: :get, params: {book_id: book}, class: 'btn btn-success'
        td = Vocabulary.count_exported(book)
= paginate @books