config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  root 'books#index'

  resources :books do
    collection do
      post :import
      get :export
      post :scrape
    end
  end

  resources :vocabularies do
    collection do
      get :book_vocab
      get :search
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/vocabulary.rb
# == Schema Information

# Table: vocabularies

# id													:bigint
# word: 											:string
# phonics: 										:string
# definition: 								:text
# book_id: 										:integer
# example: 										:text
# scraping_id: 								:integer
# export_at: 								  :datatime
# created_at: 								:datatime
# updated_at: 								:datatime

class Vocabulary < ApplicationRecord
  belongs_to :book

  def self.vocab_not_scraped?(book)
    Vocabulary.where(book_id: book.id, definition: [nil, '']).count
  end

  def self.count_done(book)
    Vocabulary.where(book_id: book.id).where.not(definition: [nil, '']).count
  end

  def self.count_exported(book)
    Vocabulary.where(book_id: book.id).where.not(export_at: nil).count
  end
end

app/controllers/vocabularies_controller.rb
class VocabulariesController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @vocabularies = Kaminari.paginate_array(Vocabulary.all.order(id: "DESC")).page(params[:page])
    @book = Book.all
  end

  def create; end

  def new; end

  def edit
    @vocabulary = Vocabulary.find(params[:id])
  end

  def update
    @vocabulary = Vocabulary.find(params[:id])
    if @vocabulary.update!(vocabulary_params)
      redirect_to vocabularies_path, notice: '保存に成功しました'
    else
      render :edit, alter: '保存に失敗しました'
    end
  end

  def destroy
    vocabulary = Vocabulary.find(params[:id])
    vocabulary.destroy ? (redirect_to request.referer, notice: "#{vocabulary.word}を削除しました。") : (redirect_to request.referer, notice: "#{vocabulary.word}の削除に失敗しました。")
  end

  def search
    @result = @q.page(params[:page])
    @book = Book.all
  end

  def book_vocab
    @book = Book.find(params[:book])
    @vocabularies = Kaminari.paginate_array(Vocabulary.where(book_id: @book.id).order(id: "DESC")).page(params[:page])
  end

  private

  def vocabulary_params
    params.require(:vocabulary).permit(:word, :phonics, :definition, :example)
  end

  def set_q
    @q = Vocabulary.ransack(book_id_eq: params[:book]).result
    @q = @q.ransack(phonics_or_definition_eq: 'not found').result if params[:not_found].present?
  end
end

app/helpers/vocabularies_helper.rb
module VocabulariesHelper
  def emphasize_not_found(any_string)
    tag.div any_string, class: any_string == 'not found' ? 'text-danger' : nil
  end
end

app/views/vocabularies/book_vocab.html.slim
h1
  | #{@book.title}
table.table
  thead
    tr
      th Word
      th Phonics
      th Definition
      th Example
      th Edit
      th Delete
  tbody
    - @vocabularies.each do |vocabulary|
      tr
        td = vocabulary.word
        td = emphasize_not_found(vocabulary.phonics)
        td = emphasize_not_found(vocabulary.definition)
        td = vocabulary.example
        td = button_to 'Edit', edit_vocabulary_path(vocabulary), method: :get, params: { vocabulary: vocabulary }, class: 'btn btn-success'
        td = button_to 'Delete', vocabulary_path(vocabulary), { method: :delete, data: {confirm: "Vocabularyを削除します。よろしいですか？"}, class: 'btn btn-danger' }
= paginate @vocabularies

app/views/vocabularies/edit.html.slim
h1
  | 単語編集
div.form-group
	= form_with model: @vocabulary do |f|
		div.form-group
			= f.label 'Word'
			= f.text_field :word, class: 'form-control'
		div.form-group
			= f.label 'Phonics'
			= f.text_field :phonics, class: 'form-control'
		div.form-group
			= f.label 'Definition'
			= f.text_field :definition, class: 'form-control'
		div.form-group
			= f.label 'Example'
			= f.text_field :example, class: 'form-control'
		div.form-group
			= f.submit '保存', class: 'btn btn-primary'

app/views/vocabularies/index.html.slim
h1
  | 単語一覧
table.table
  thead
    tr
			th Book
			th Word
			th Phonics
			th Definition
			th Example
			th Edit
			th Delete
  tbody
    - @vocabularies.each do |vocabulary|
      tr
        td = link_to "#{Book.book_title?(vocabulary.book_id)}", book_vocab_vocabularies_path(book: vocabulary.book_id), {class: "text-decoration-none"}
        td = vocabulary.word
        td = emphasize_not_found(vocabulary.phonics)
        td = emphasize_not_found(vocabulary.definition)
        td = vocabulary.example
        td = button_to 'Edit', edit_vocabulary_path(vocabulary), method: :get, class: 'btn btn-success'
        td = button_to 'Delete', vocabulary_path(vocabulary), { method: :delete, data: {confirm: "Vocabularyを削除します。よろしいですか？"}, class: 'btn btn-danger' }
= paginate @vocabularies

app/views/vocabularies/search.html.slim
h1
  | 単語一覧

= form_with url: search_vocabularies_path, method: :get do |f|
	div.col-3
		div.form-group
			= f.label :book, 'Book Title'
			= f.collection_select(:book, @book, :id, :title, {:include_blank => true}, {class: 'form-select'})
		div.form-check
			= check_box_tag(:not_found, 1, false, class: 'form-check-input')
			= label_tag :not_found, "Not Found"
		div.form-group
			= f.submit 'Search', class: "btn btn-success"

table.table
  thead
    tr
			th Book
			th Word
			th Phonics
			th Definition
			th Example
			th Edit
			th Delete
  tbody
    - @result.each do |vocabulary|
      tr
        td = link_to "#{Book.book_title?(vocabulary.book_id)}", book_vocab_vocabularies_path(book: vocabulary.book_id), {class: "text-decoration-none"}
        td = vocabulary.word
        td = emphasize_not_found(vocabulary.phonics)
        td = emphasize_not_found(vocabulary.definition)
        td = vocabulary.example
        td = button_to 'Edit', edit_vocabulary_path(vocabulary), method: :get, class: 'btn btn-success'
        td = button_to 'Delete', vocabulary_path(vocabulary), { method: :delete, data: {confirm: "Vocabularyを削除します。よろしいですか？"}, class: 'btn btn-danger' }
= paginate @result