config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: "/sidekiq"

  root 'books#index'

  resources :books do
    collection do
      post :import
      get :export
      post :scrape
    end
  end

  resources :vocabularies do
    collection do
      get :book_vocab
      get :search
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Myapp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
		nav.navbar.navbar-expand-lg.navbar-light.bg-success
			a.navbar-brand.text-white[href="#"]
				| KindleToAnki
			button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation"]
				span.navbar-toggler-icon
			#navbarNavAltMarkup.collapse.navbar-collapse
				= link_to "Home", root_path, {class: "nav-item nav-link text-white"}
				= link_to "Vocabulary", vocabularies_path, {class: "nav-item nav-link text-white"}
					/ span.sr-only
					/ 	| (current)
					/ a.nav-item.nav-link.text-white[href="#"]
					/ 	| Features
					/ a.nav-item.nav-link.text-white[href="#"]
					/ 	| Pricing
					/ a.nav-item.nav-link.text-white.disabled[href="#"]
					/ 	| Disabled

		.notifications
			- flash.each do |key, value|
				= content_tag(:div, value, class: key)
		div.container
			= yield